### PR TITLE
fix: 211 kahn, tarjan algorithm for topological sort

### LINKED ISSUE #211: Components push is super slow on single-file mode
I have a space with 221 blocks (including 17 folders and extensive whitelisting). When running components push using the new beta CLI in single-file mode, I encountered several issues:

1. [performance] The command seems super slow in general. It seems it iterates through all of components in the list and does lots of requests where each tasks ~1.5-2s. The current CLI was way way faster!

Image
 
I was 10 minutes ⚠ ❗ in and I still got an error:

Image

2. [validation] Validation error (`Component ... not found`) occurs at runtime (during iteration), but could be performed statically upfront.

I haven't checked code yet but, the new CLI seems smarter in traversing whitelist groups and blocks, but errors only surface during runtime - forcing a full re-run of the components push process, which adds ~10 minutes of waiting after an error was surfaced and manually fixed. These errors typically stem from outdated JSON or misconfigurations (e.g. whitelists referencing deleted blocks). Since removing a block doesn't update associated whitelists in the CMS, this leads to mismatches that could be caught earlier with static validation.

I believe the whitelist issue is likely to affect many users—not just during migration from v3 to v4, but also in regular workflows. For example, if someone deletes a block, its technical name might still remain in other components’ whitelist arrays.

Is there any cleanup happening automatically when a block is removed? If not, I strongly recommend introducing a static validation step before running components push. This would help catch broken references early and avoid wasting time on lengthy runtime validations.

This could either be part of components push or introduced as a separate components validate command. Otherwise, if static validation isn’t feasible, perhaps whitelist references should not be strictly validated at all (just warnings thrown?)

3. [DX] When pushing components in single-file mode, why is the whitelist iterated for each component? It seems like some blocks might be pushed multiple times, leading to excessive outgoing requests. Maybe there should be some in-memory array and then push component ONLY once. If this is a full space configuration push, a one-time static validation should be enough. Once validated, the push could proceed as efficiently as in the old CLI, without redundant operations or iterations.

**Old CLI speed is typically 800~1000ms per each request to push, hence it's ~4 minutes to push all of my 221 blocks and all those 17 folders.**

### LINKED ISSUE #228: [v4] Pushing component from space 1 to space 2 removes its default preset
This is a bug in 4.0.0-beta.4

**Current behavior:**

Here's how I pull components:
```
storyblok components pull --space 1 --separate-files --suffix 1
```

Here's how I push components
```
components push --space 2 --from 1 --suffix 1 --separate-files --verbose
```

I have some components with presets, and some of those presets are marked as default. For example this is a part of a component schema that has a preset, from space 1:

```
  "all_presets": [
    {
      "id": 16,
      "name": "My Preset",
      "component_id": 333,
      "some_field": null,
    }
  ],
  "preset_id": 16,
```

On space 2, the same snippet is something like this:

```
  "all_presets": [
    {
      "id": 24,
      "name": "My Preset",
      "component_id": 512,
      "some_field": null,
    }
  ],
  "preset_id": 24,
```

When I push this component from space 1 to space 2, the field `preset_id` on the component schema becomes nullified. This effectively unmarks a preset as a default. The component no longer has a default preset, but all of its presets are still there.

```
  "all_presets": [
    {
      "id": 24,
      "name": "My Preset",
      "component_id": 512,
      "some_field": null,
    }
  ],
  "preset_id": null,
```

This happens regardless of whether I push a single component or all of them. This happens for all components that have default presets.

It doesn't happen if I push a component from space 1 to space 1.

**Expected behavior:**

I would expect the CLI to translate all preset ids from space 1 to preset ids from space 2 when pushing, based on preset names. I would expect all components to still have the chosen default presets after pushing from one space to another.

### LINKED ISSUE #229: [v4] Pushing component from space 1 to space 2 fails if component has internal_tag_ids
This is a bug in 4.0.0-beta.4

**Current behavior:**

Here's how I pull components:
```
storyblok components pull --space 1 --separate-files --suffix 1
```

Here's how I push components
```
components push --space 2 --from 1 --suffix 1 --separate-files --verbose
```

I have some components with tags (`internal_tag_ids`) , for example `"internal_tag_ids": ["78"]` on space 1. A tag with the same name exists on space 2 and has id of `"190"` (I'm making up the values as an example). That component also already exists on space 2 and has `"internal_tag_ids": ["190"]` before I try to push.

When I try to push this component from space 1 to space 2, it crashes with the error:

```
▲ error Failed to update component enterprise_two_text 
▲ error internal_tag_ids: Invalid internal_tag, there is at least one internal_tag not found in our database 
▲ error API Error: The request was well-formed but was unable to be followed due to semantic errors {
  name: 'API Error',
  message: 'Failed to update component enterprise_two_text',
  httpCode: 422,
  cause: 'The request was well-formed but was unable to be followed due to semantic errors',
  errorId: 'unprocessable_entity',
  stack: 'API Error: Failed to update component enterprise_two_text\n' +
    '    at handleAPIError (file:///Users/angelikacathor/Documents/code/storyblok-website/node_modules/storyblok-next/dist/index.mjs:174:15)\n' +
    '    at updateComponent (file:///Users/angelikacathor/Documents/code/storyblok-website/node_modules/storyblok-next/dist/index.mjs:1039:5)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async upsertComponent (file:///Users/angelikacathor/Documents/code/storyblok-website/node_modules/storyblok-next/dist/index.mjs:1051:18)\n' +
    '    at async handleComponents (file:///Users/angelikacathor/Documents/code/storyblok-website/node_modules/storyblok-next/dist/index.mjs:1987:9)\n' +
    '    at async Command.<anonymous> (file:///Users/angelikacathor/Documents/code/storyblok-website/node_modules/storyblok-next/dist/index.mjs:2087:31)',
  responseData: {
    internal_tag_ids: [
      'Invalid internal_tag, there is at least one internal_tag not found in our database'
    ]
  }
}
```

This happens regardless of whether I push a single component or all of them. This happens for all components that have default presets.

It doesn't happen if I push a component from space 1 to space 1.

**Expected behavior:**

I would expect the CLI to translate all tag ids from space 1 to tag ids from space 2 when pushing, based on tag names. This definitely already happens when pushing `"component_tag_whitelist"` values on components, but maybe it's buggy with `"internal_tag_ids"`?

### PR DESCRIPTION
**Pull request by imranolas**
This PR introduces a complete refactor of the dependency tracking for pushing components using Kahn's topological sorting algorithm in combination with the Tarjan circular dependencies algorithm

This PR greatly improves the performance and should enable:

- Components Push
- Internal Tags
- Folder trees
- Presets
- Whitelists
  - Tags
  - Folders
  - Components
  
  
  ## Out of scope
  
  Validate which resources need to be update, this is going to be implemented in the future

### CODE REVIEW

**Review by alvarosabu — APPROVED** [review]
QG Results:

- [x] Push all components from consolidated files
- [x] Push all components with separate files
- [x] Push individual component from consolidated files
- [x] Push individual component from separate files
- [x] Push filtered components from consolidated files
- [x] Push filtered components from separate files

**Comment by alvarosabu** [comment]
Performance audit **Before and after**

Screenshot 2025-06-17 at 09 55 26

  | Before | Retry-mechanism | Kahn + Tarjan | %
-- | -- | -- | -- | --
Total requests | 433 | 305 | 158 | -63.51%
Time | 53.764s | 37.845s | 19.2s | -64.29%

File: src/commands/components/push/progress-display.ts [hunk 1]
```diff
@@ -0,0 +1,138 @@
...
+
+      case 'complete': {
+        this.clearProgress();
+        const { updated, unchanged, failed } = event.summary;
+
+        // Calculate elapsed time if startTime was recorded
+        const elapsedTime = this.startTime ? Date.now() - this.startTime : null;
+        const timeString = elapsedTime ? this.formatElapsedTime(elapsedTime) : '';
+
+        konsola.ok(`Completed: ${updated} updated, ${unchanged} unchanged, ${failed} failed${timeString ? ` in ${timeString}` : ''}`, true);
```
Comment (alvarosabu) [inline src/commands/components/push/progress-display.ts:81]: @imranolas should we still show the unchanged?

**Comment by edvinasjurele** [comment]
Just so you know, I tried this version on my space

image

```
✔ Completed: 243 updated, 0 unchanged, 0 failed in 1m 4s

273 requests made
```

**1 minute** is an awesome speed 🚀 🚀 Good job, guys!

File: src/commands/components/push/progress-display.ts (hunk 1 above)
Comment (imranolas) [reply src/commands/components/push/progress-display.ts:81]: Good catch. We can remove that.
